#!/bin/bash

if [ -x /usr/bin/snapp ]; then
	/usr/bin/snap $@
else
	echo "SNAP is not currently installed."
	echo "SNAP is a universal package manager that works on almost every linux distro"
	echo " enabling you to access many programs not currently delivered by"
	echo " the official Parrot Security repository."
	echo
	echo "SNAP is develped by Canonical, the company behind Ubuntu, and it includes"
	echo " telemetry that may compromise your privacy or hurt your freedom."
	echo " It also allows you to easily install proprietary software"
	echo " that may ship further telemetry, perform invasive data collection on you"
	echo " and even install malware on your computer."
	echo
	echo "Please proceed with the installation of SNAP"
	echo "only if such conditions are ok for you"
	echo "and you accept the consequences."
	echo
	echo "press ENTER to continue, or CTRL+C to exit"
	read
	apt update
	apt -y install snapd
	/usr/bin/snap $@
fi
