bin/* usr/bin/
localbin/* usr/local/bin/
dconf usr/lib/parrot-skel/etc/
skel usr/lib/parrot-skel/etc/

app_configs/bash.bashrc /etc/
app_configs/vimrc /etc/vim/

system_configs/etc/NetworkManager/conf.d/90-dns-none.conf etc/NetworkManager/conf.d/
system_configs/Xsession.d/* etc/X11/Xsession.d/
system_configs/udev-rules/* etc/udev/rules.d/
system_configs/profile.d/* etc/profile.d/
system_configs/apt/* etc/apt/
system_configs/grub.default etc/default/grub.d/
