#!/bin/bash

set -e

# configure bashrc
mkdir -p /etc/skel
mkdir -p /usr/lib/parrot-skel/etc/skel
cat /etc/bashrc > /etc/skel/.bashrc
cat /etc/bashrc > /usr/lib/parrot-skel/etc/skel/.bashrc

# Configure plymouth theme
[ ! -x /usr/sbin/plymouth-set-default-theme ] || /usr/sbin/plymouth-set-default-theme parrot || true

# Install python alias
if [ ! $(update-alternatives --list python | grep python3) ]; then
    update-alternatives --install /usr/bin/python python /usr/bin/python3 50
fi
