#!/bin/bash

set -e

# Install python alias
if [ $(which python3); then
    if [ ! $(update-alternatives --list python | grep python3) ]; then
        update-alternatives --install /usr/bin/python python /usr/bin/python3 50
    fi
fi


mkdir -p /etc/dconf/db/local.d/
cp -r /usr/lib/parrot-skel/etc/dconf/db/local.d/parrot-skel /etc/dconf/db/local.d/parrot-skel

dconf compile /etc/dconf/db/local /etc/dconf/db/local.d/
dconf compile /etc/skel/.config/dconf/user /etc/dconf/db/local.d/

rsync -a --delete /usr/lib/parrot-skel/etc/skel/ /etc/skel/
rsync -a /etc/skel/ /root/
