#!/bin/bash

set -e

# configure bashrc
mkdir -p /etc/skel
mkdir -p /usr/lib/parrot-skel/etc/skel
cat /etc/bashrc > /etc/skel/.bashrc
cat /etc/bashrc > /usr/lib/parrot-skel/etc/skel/.bashrc

#configure firejail sandboxes
[ ! -x /usr/bin/firecfg ] || /usr/bin/firecfg || true

# configure plymouth theme
[ ! -x /usr/sbin/plymouth-set-default-theme ] || /usr/sbin/plymouth-set-default-theme parrot || true
